services:
  database_postgres:
    image: postgres:18
    restart: always
    networks:
      - smartcraft_network
    ports:
      - "65432:5432"
    environment:
      POSTGRES_PASSWORD: ${ConnectionStrings__ServicesDB__Password}
      POSTGRES_USER: ${ConnectionStrings__ServicesDB__Username}
      POSTGRES_DB: ${ConnectionStrings__ServicesDB__Database}

  keycloak:
    container_name: keycloak_app
    image: quay.io/keycloak/keycloak:latest
    restart: always
    ports:
    - "8080:8080"
    volumes:
      - "/etc/ssl/keycloak/:/etc/x509/https"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      # KC_HOSTNAME: localhost
      KC_DB_URL: jdbc:postgresql://database_postgres:5432/smartcraft
      KC_DB: postgres
      KC_DB_USERNAME:  ${ConnectionStrings__ServicesDB__Username}
      KC_DB_PASSWORD: ${ConnectionStrings__ServicesDB__Password}
    depends_on:
      - database_postgres
    networks:
      - smartcraft_network
    command:
      - start-dev

  smartcraft.api:
    networks:
      - smartcraft_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__ServicesDB=$ConnectionStrings__ServicesDB
      - Keycloak__Authority=$Keycloak__Authority
      - Keycloak__Audience=$Keycloak__Audience
    ports:
      - "9999:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - database_postgres

networks:
  smartcraft_network:
    driver: bridge
